# air.toml
root = "." 
tmp_dir = "tmp" 

[build] 
  bin = "main" 
  cmd = "go build -o {{.Output}} {{.Input}}" 
  exclude = ["tmp/*", "client/*"]  
  include = ["**/*.go"] 
  ignore = ["tmp/*"] 

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true